# Generated by Django 6.0.3 on 2026-03-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('MESA', 'Puesto Individual'), ('SALA', 'Sala de Reuniones'), ('OFICINA', 'Oficina Privada')], default='MESA', max_length=10)),
                ('capacidad', models.IntegerField(default=1)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
